export const vars = {
  API_URL: 'http://localhost:3000',
  WEB_URL: 'https://d37f1pgihrw3s3.cloudfront.net',
  VERSION: 'v1',
  STAGE: 'dev',
  DATABASE_URL: process.env.DATABASE_URL,
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
  GITHUB_CLIENT_ID: process.env.GITHUB_CLIENT_ID,
  GITHUB_CLIENT_SECRET: process.env.GITHUB_CLIENT_SECRET,
  MICROSOFT_CLIENT_ID: process.env.MICROSOFT_CLIENT_ID,
  MICROSOFT_CLIENT_SECRET: process.env.MICROSOFT_CLIENT_SECRET,
  JWT_ACCESS_TOKEN_EXPIRATION_TIME:
    process.env.JWT_ACCESS_TOKEN_EXPIRATION_TIME,
  JWT_ACCESS_TOKEN_SECRET: process.env.JWT_ACCESS_TOKEN_SECRET,
  JWT_REFRESH_TOKEN_EXPIRATION_TIME:
    process.env.JWT_REFRESH_TOKEN_EXPIRATION_TIME,
  JWT_REFRESH_TOKEN_SECRET: process.env.JWT_REFRESH_TOKEN_SECRET,
  FORGET_PASSWORD_SALT: process.env.FORGET_PASSWORD_SALT,
  JWT_FORGET_PASSWORD_SECRET: process.env.JWT_FORGET_PASSWORD_SECRET,
  JWT_FORGET_PASSWORD_EXPIRATION_TIME:
    process.env.JWT_FORGET_PASSWORD_EXPIRATION_TIME,
  VERIFY_EMAIL_SECRET: process.env.VERIFY_EMAIL_SECRET,
  VERIFY_EMAIL_EXPIRATION_TIME: process.env.VERIFY_EMAIL_EXPIRATION_TIME,
  VERIFY_OAUTH_SECRET: process.env.VERIFY_OAUTH_SECRET,
  VERIFY_OAUTH_EXPIRATION_TIME: process.env.VERIFY_OAUTH_EXPIRATION_TIME,
  AWS_REGION: process.env.AWS_REGION,
};
